package org.pfccap.education.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "ANSWERS_QUESTION".
 */
public class AnswersQuestion {

    private Long id;
    private String idQuestion;
    private String description;
    private Boolean value;
    private Integer points;
    private boolean enable = true;

    public boolean isEnable() {
        return enable;
    }

    public void setEnable(boolean enable) {
        this.enable = enable;
    }


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public AnswersQuestion() {
    }

    public AnswersQuestion(Long id) {
        this.id = id;
    }

    public AnswersQuestion(Long id, String idQuestion, String description, Boolean value, Integer points) {
        this.id = id;
        this.idQuestion = idQuestion;
        this.description = description;
        this.value = value;
        this.points = points;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIdQuestion() {
        return idQuestion;
    }

    public void setIdQuestion(String idQuestion) {
        this.idQuestion = idQuestion;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Boolean getValue() {
        return value;
    }

    public void setValue(Boolean value) {
        this.value = value;
    }

    public Integer getPoints() {
        return points;
    }

    public void setPoints(Integer points) {
        this.points = points;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
