package org.pfccap.education.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "CIUDADES".
 */
public class Ciudades {

    private Long id;
    private Long idCity;
    private String idPais;
    private String name;
    private Boolean state;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Ciudades() {
    }

    public Ciudades(Long id) {
        this.id = id;
    }

    public Ciudades(Long id, Long idCity, String idPais, String name, Boolean state) {
        this.id = id;
        this.idCity = idCity;
        this.idPais = idPais;
        this.name = name;
        this.state = state;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getIdCity() {
        return idCity;
    }

    public void setIdCity(Long idCity) {
        this.idCity = idCity;
    }

    public String getIdPais() {
        return idPais;
    }

    public void setIdPais(String idPais) {
        this.idPais = idPais;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean getState() {
        return state;
    }

    public void setState(Boolean state) {
        this.state = state;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
