package org.pfccap.education.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import org.pfccap.education.dao.UserDao;
import org.pfccap.education.dao.QuestionDao;
import org.pfccap.education.dao.AnswersQuestionDao;
import org.pfccap.education.dao.SecondAnswerDao;
import org.pfccap.education.dao.GiftDao;
import org.pfccap.education.dao.PaisesDao;
import org.pfccap.education.dao.CiudadesDao;
import org.pfccap.education.dao.ComunasDao;
import org.pfccap.education.dao.EseDao;
import org.pfccap.education.dao.IPSDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        UserDao.createTable(db, ifNotExists);
        QuestionDao.createTable(db, ifNotExists);
        AnswersQuestionDao.createTable(db, ifNotExists);
        SecondAnswerDao.createTable(db, ifNotExists);
        GiftDao.createTable(db, ifNotExists);
        PaisesDao.createTable(db, ifNotExists);
        CiudadesDao.createTable(db, ifNotExists);
        ComunasDao.createTable(db, ifNotExists);
        EseDao.createTable(db, ifNotExists);
        IPSDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        UserDao.dropTable(db, ifExists);
        QuestionDao.dropTable(db, ifExists);
        AnswersQuestionDao.dropTable(db, ifExists);
        SecondAnswerDao.dropTable(db, ifExists);
        GiftDao.dropTable(db, ifExists);
        PaisesDao.dropTable(db, ifExists);
        CiudadesDao.dropTable(db, ifExists);
        ComunasDao.dropTable(db, ifExists);
        EseDao.dropTable(db, ifExists);
        IPSDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(UserDao.class);
        registerDaoClass(QuestionDao.class);
        registerDaoClass(AnswersQuestionDao.class);
        registerDaoClass(SecondAnswerDao.class);
        registerDaoClass(GiftDao.class);
        registerDaoClass(PaisesDao.class);
        registerDaoClass(CiudadesDao.class);
        registerDaoClass(ComunasDao.class);
        registerDaoClass(EseDao.class);
        registerDaoClass(IPSDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
