package org.pfccap.education.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import org.pfccap.education.dao.User;
import org.pfccap.education.dao.Questions;
import org.pfccap.education.dao.Answers;

import org.pfccap.education.dao.UserDao;
import org.pfccap.education.dao.QuestionsDao;
import org.pfccap.education.dao.AnswersDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig questionsDaoConfig;
    private final DaoConfig answersDaoConfig;

    private final UserDao userDao;
    private final QuestionsDao questionsDao;
    private final AnswersDao answersDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        questionsDaoConfig = daoConfigMap.get(QuestionsDao.class).clone();
        questionsDaoConfig.initIdentityScope(type);

        answersDaoConfig = daoConfigMap.get(AnswersDao.class).clone();
        answersDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        questionsDao = new QuestionsDao(questionsDaoConfig, this);
        answersDao = new AnswersDao(answersDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Questions.class, questionsDao);
        registerDao(Answers.class, answersDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        questionsDaoConfig.getIdentityScope().clear();
        answersDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public QuestionsDao getQuestionsDao() {
        return questionsDao;
    }

    public AnswersDao getAnswersDao() {
        return answersDao;
    }

}
