package org.pfccap.education.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import org.pfccap.education.dao.User;
import org.pfccap.education.dao.Question;
import org.pfccap.education.dao.AnswersQuestion;
import org.pfccap.education.dao.SecondAnswer;
import org.pfccap.education.dao.Gift;
import org.pfccap.education.dao.Paises;
import org.pfccap.education.dao.Ciudades;
import org.pfccap.education.dao.Comunas;
import org.pfccap.education.dao.Ese;
import org.pfccap.education.dao.IPS;

import org.pfccap.education.dao.UserDao;
import org.pfccap.education.dao.QuestionDao;
import org.pfccap.education.dao.AnswersQuestionDao;
import org.pfccap.education.dao.SecondAnswerDao;
import org.pfccap.education.dao.GiftDao;
import org.pfccap.education.dao.PaisesDao;
import org.pfccap.education.dao.CiudadesDao;
import org.pfccap.education.dao.ComunasDao;
import org.pfccap.education.dao.EseDao;
import org.pfccap.education.dao.IPSDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig questionDaoConfig;
    private final DaoConfig answersQuestionDaoConfig;
    private final DaoConfig secondAnswerDaoConfig;
    private final DaoConfig giftDaoConfig;
    private final DaoConfig paisesDaoConfig;
    private final DaoConfig ciudadesDaoConfig;
    private final DaoConfig comunasDaoConfig;
    private final DaoConfig eseDaoConfig;
    private final DaoConfig iPSDaoConfig;

    private final UserDao userDao;
    private final QuestionDao questionDao;
    private final AnswersQuestionDao answersQuestionDao;
    private final SecondAnswerDao secondAnswerDao;
    private final GiftDao giftDao;
    private final PaisesDao paisesDao;
    private final CiudadesDao ciudadesDao;
    private final ComunasDao comunasDao;
    private final EseDao eseDao;
    private final IPSDao iPSDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        questionDaoConfig = daoConfigMap.get(QuestionDao.class).clone();
        questionDaoConfig.initIdentityScope(type);

        answersQuestionDaoConfig = daoConfigMap.get(AnswersQuestionDao.class).clone();
        answersQuestionDaoConfig.initIdentityScope(type);

        secondAnswerDaoConfig = daoConfigMap.get(SecondAnswerDao.class).clone();
        secondAnswerDaoConfig.initIdentityScope(type);

        giftDaoConfig = daoConfigMap.get(GiftDao.class).clone();
        giftDaoConfig.initIdentityScope(type);

        paisesDaoConfig = daoConfigMap.get(PaisesDao.class).clone();
        paisesDaoConfig.initIdentityScope(type);

        ciudadesDaoConfig = daoConfigMap.get(CiudadesDao.class).clone();
        ciudadesDaoConfig.initIdentityScope(type);

        comunasDaoConfig = daoConfigMap.get(ComunasDao.class).clone();
        comunasDaoConfig.initIdentityScope(type);

        eseDaoConfig = daoConfigMap.get(EseDao.class).clone();
        eseDaoConfig.initIdentityScope(type);

        iPSDaoConfig = daoConfigMap.get(IPSDao.class).clone();
        iPSDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        questionDao = new QuestionDao(questionDaoConfig, this);
        answersQuestionDao = new AnswersQuestionDao(answersQuestionDaoConfig, this);
        secondAnswerDao = new SecondAnswerDao(secondAnswerDaoConfig, this);
        giftDao = new GiftDao(giftDaoConfig, this);
        paisesDao = new PaisesDao(paisesDaoConfig, this);
        ciudadesDao = new CiudadesDao(ciudadesDaoConfig, this);
        comunasDao = new ComunasDao(comunasDaoConfig, this);
        eseDao = new EseDao(eseDaoConfig, this);
        iPSDao = new IPSDao(iPSDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Question.class, questionDao);
        registerDao(AnswersQuestion.class, answersQuestionDao);
        registerDao(SecondAnswer.class, secondAnswerDao);
        registerDao(Gift.class, giftDao);
        registerDao(Paises.class, paisesDao);
        registerDao(Ciudades.class, ciudadesDao);
        registerDao(Comunas.class, comunasDao);
        registerDao(Ese.class, eseDao);
        registerDao(IPS.class, iPSDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        questionDaoConfig.getIdentityScope().clear();
        answersQuestionDaoConfig.getIdentityScope().clear();
        secondAnswerDaoConfig.getIdentityScope().clear();
        giftDaoConfig.getIdentityScope().clear();
        paisesDaoConfig.getIdentityScope().clear();
        ciudadesDaoConfig.getIdentityScope().clear();
        comunasDaoConfig.getIdentityScope().clear();
        eseDaoConfig.getIdentityScope().clear();
        iPSDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public QuestionDao getQuestionDao() {
        return questionDao;
    }

    public AnswersQuestionDao getAnswersQuestionDao() {
        return answersQuestionDao;
    }

    public SecondAnswerDao getSecondAnswerDao() {
        return secondAnswerDao;
    }

    public GiftDao getGiftDao() {
        return giftDao;
    }

    public PaisesDao getPaisesDao() {
        return paisesDao;
    }

    public CiudadesDao getCiudadesDao() {
        return ciudadesDao;
    }

    public ComunasDao getComunasDao() {
        return comunasDao;
    }

    public EseDao getEseDao() {
        return eseDao;
    }

    public IPSDao getIPSDao() {
        return iPSDao;
    }

}
