package org.pfccap.education.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "GIFT".
 */
public class Gift {

    private Long id;
    private String points;
    private String gift;
    private Integer order;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Gift() {
    }

    public Gift(Long id) {
        this.id = id;
    }

    public Gift(Long id, String points, String gift, Integer order) {
        this.id = id;
        this.points = points;
        this.gift = gift;
        this.order = order;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPoints() {
        return points;
    }

    public void setPoints(String points) {
        this.points = points;
    }

    public String getGift() {
        return gift;
    }

    public void setGift(String gift) {
        this.gift = gift;
    }

    public Integer getOrder() {
        return order;
    }

    public void setOrder(Integer order) {
        this.order = order;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
