package org.pfccap.education.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "IPS".
 */
public class IPS {

    private Long id;
    private Long idIps;
    private String idPais;
    private String idCiudad;
    private String idEse;
    private String name;
    private Boolean state;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public IPS() {
    }

    public IPS(Long id) {
        this.id = id;
    }

    public IPS(Long id, Long idIps, String idPais, String idCiudad, String idEse, String name, Boolean state) {
        this.id = id;
        this.idIps = idIps;
        this.idPais = idPais;
        this.idCiudad = idCiudad;
        this.idEse = idEse;
        this.name = name;
        this.state = state;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getIdIps() {
        return idIps;
    }

    public void setIdIps(Long idIps) {
        this.idIps = idIps;
    }

    public String getIdPais() {
        return idPais;
    }

    public void setIdPais(String idPais) {
        this.idPais = idPais;
    }

    public String getIdCiudad() {
        return idCiudad;
    }

    public void setIdCiudad(String idCiudad) {
        this.idCiudad = idCiudad;
    }

    public String getIdEse() {
        return idEse;
    }

    public void setIdEse(String idEse) {
        this.idEse = idEse;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean getState() {
        return state;
    }

    public void setState(Boolean state) {
        this.state = state;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
