package org.pfccap.education.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "IPS".
 */
public class IPS {

    private Long id;
    private Integer idIps;
    private Integer idPais;
    private Integer idCiudad;
    private Integer idEse;
    private String name;
    private Boolean state;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public IPS() {
    }

    public IPS(Long id) {
        this.id = id;
    }

    public IPS(Long id, Integer idIps, Integer idPais, Integer idCiudad, Integer idEse, String name, Boolean state) {
        this.id = id;
        this.idIps = idIps;
        this.idPais = idPais;
        this.idCiudad = idCiudad;
        this.idEse = idEse;
        this.name = name;
        this.state = state;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getIdIps() {
        return idIps;
    }

    public void setIdIps(Integer idIps) {
        this.idIps = idIps;
    }

    public Integer getIdPais() {
        return idPais;
    }

    public void setIdPais(Integer idPais) {
        this.idPais = idPais;
    }

    public Integer getIdCiudad() {
        return idCiudad;
    }

    public void setIdCiudad(Integer idCiudad) {
        this.idCiudad = idCiudad;
    }

    public Integer getIdEse() {
        return idEse;
    }

    public void setIdEse(Integer idEse) {
        this.idEse = idEse;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean getState() {
        return state;
    }

    public void setState(Boolean state) {
        this.state = state;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
