package org.pfccap.education.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "PAISES".
 */
public class Paises {

    private Long id;
    private Integer idCountry;
    private String name;
    private Boolean state;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Paises() {
    }

    public Paises(Long id) {
        this.id = id;
    }

    public Paises(Long id, Integer idCountry, String name, Boolean state) {
        this.id = id;
        this.idCountry = idCountry;
        this.name = name;
        this.state = state;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getIdCountry() {
        return idCountry;
    }

    public void setIdCountry(Integer idCountry) {
        this.idCountry = idCountry;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean getState() {
        return state;
    }

    public void setState(Boolean state) {
        this.state = state;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
