package org.pfccap.education.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "QUESTION".
 */
public class Question {

    private Long id;
    private String code;
    private String question;
    private Integer typeCancer;
    private String typeQuestion;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Question() {
    }

    public Question(Long id) {
        this.id = id;
    }

    public Question(Long id, String code, String question, Integer typeCancer, String typeQuestion) {
        this.id = id;
        this.code = code;
        this.question = question;
        this.typeCancer = typeCancer;
        this.typeQuestion = typeQuestion;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getQuestion() {
        return question;
    }

    public void setQuestion(String question) {
        this.question = question;
    }

    public Integer getTypeCancer() {
        return typeCancer;
    }

    public void setTypeCancer(Integer typeCancer) {
        this.typeCancer = typeCancer;
    }

    public String getTypeQuestion() {
        return typeQuestion;
    }

    public void setTypeQuestion(String typeQuestion) {
        this.typeQuestion = typeQuestion;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
