package org.pfccap.education.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "QUESTION".
 */
public class Question {

    private Long id;
    private String idquest;
    private String txtQuestion;
    private String typeCancer;
    private String typeQuestion;
    private Integer order;
    private Boolean enable;
    private String info;
    private String answers;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Question() {
    }

    public Question(Long id) {
        this.id = id;
    }

    public Question(Long id, String idquest, String txtQuestion, String typeCancer, String typeQuestion, Integer order, Boolean enable, String info, String answers) {
        this.id = id;
        this.idquest = idquest;
        this.txtQuestion = txtQuestion;
        this.typeCancer = typeCancer;
        this.typeQuestion = typeQuestion;
        this.order = order;
        this.enable = enable;
        this.info = info;
        this.answers = answers;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIdquest() {
        return idquest;
    }

    public void setIdquest(String idquest) {
        this.idquest = idquest;
    }

    public String getTxtQuestion() {
        return txtQuestion;
    }

    public void setTxtQuestion(String txtQuestion) {
        this.txtQuestion = txtQuestion;
    }

    public String getTypeCancer() {
        return typeCancer;
    }

    public void setTypeCancer(String typeCancer) {
        this.typeCancer = typeCancer;
    }

    public String getTypeQuestion() {
        return typeQuestion;
    }

    public void setTypeQuestion(String typeQuestion) {
        this.typeQuestion = typeQuestion;
    }

    public Integer getOrder() {
        return order;
    }

    public void setOrder(Integer order) {
        this.order = order;
    }

    public Boolean getEnable() {
        return enable;
    }

    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    public String getInfo() {
        return info;
    }

    public void setInfo(String info) {
        this.info = info;
    }

    public String getAnswers() {
        return answers;
    }

    public void setAnswers(String answers) {
        this.answers = answers;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
